### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by mbanco** [jtilly/knitroR#1]
Could you explain how to install the knitroR package in R for Windows and knitro 9.0 32 bit?

Thank a lots.

**Comment by jtilly** [comment]
I just started working on this package. For now, this only works under Linux and Mac OS X.

**Comment by jtilly** [comment]
I got the package to work under Windows 7 (32bit) and Knitro 9.1. Installation instructions are [here](https://github.com/jtilly/knitroR/blob/master/README.md). Installing the package for older versions of Knitro (such as 9.0) requires some manual adjustments. I put my best guess for what these adjustments are into the Readme, but I'm not able to test it, because I don't have access to an older version of Knitro.

**Comment by mbanco** [comment]
Hi Jan,
I have the next message when I try to compile de package:

install.packages("C:/knitroR-master", repos = NULL, type="source")
- installing _source_ package 'knitroR' ...
  *\* libs

**\* arch - i386
cygwin warning:
  MS-DOS style path detected: C:/R/etc/i386/Makeconf
  Preferred POSIX equivalent is: /cygdrive/c/R/etc/i386/Makeconf
  CYGWIN environment variable option "nodosfilewarning" turns off this
warning.
  Consult the user's guide for more details about POSIX paths:
    http://cygwin.com/cygwin-ug-net/using.html#using-pathnames
g++ -m32 -I"C:/R/include" -DNDEBUG    -I"C:/R/library/Rcpp/include"
-I"d:/RCompile/CRANpkg/extralibs64/local/include"  -I"C:\Program Files
(x86)\Ziena\KNITRO900/include"   -O2 -Wall  -mtune=core2 -c RcppExports.cpp
-o RcppExports.o
g++ -m32 -I"C:/R/include" -DNDEBUG    -I"C:/R/library/Rcpp/include"
-I"d:/RCompile/CRANpkg/extralibs64/local/include"  -I"C:\Program Files
(x86)\Ziena\KNITRO900/include"   -O2 -Wall  -mtune=core2 -c knitro.cpp -o
knitro.o
g++ -m32 -shared -s -static-libgcc -o knitroR.dll tmp.def RcppExports.o
knitro.o C:\Program Files (x86)\Ziena\KNITRO900\lib\knitro900.lib
-Ld:/RCompile/CRANpkg/extralibs64/local/lib/i386
-Ld:/RCompile/CRANpkg/extralibs64/local/lib -LC:/R/bin/i386 -lR
installing to C:/R/library/knitroR/libs/i386

**\* arch - x64
cygwin warning:
  MS-DOS style path detected: C:/R/etc/x64/Makeconf
  Preferred POSIX equivalent is: /cygdrive/c/R/etc/x64/Makeconf
  CYGWIN environment variable option "nodosfilewarning" turns off this
warning.
  Consult the user's guide for more details about POSIX paths:
    http://cygwin.com/cygwin-ug-net/using.html#using-pathnames
g++ -m64 -I"C:/R/include" -DNDEBUG    -I"C:/R/library/Rcpp/include"
-I"d:/RCompile/CRANpkg/extralibs64/local/include"  -I"C:\Program Files
(x86)\Ziena\KNITRO900/include"   -O2 -Wall  -mtune=core2 -c RcppExports.cpp
-o RcppExports.o
g++ -m64 -I"C:/R/include" -DNDEBUG    -I"C:/R/library/Rcpp/include"
-I"d:/RCompile/CRANpkg/extralibs64/local/include"  -I"C:\Program Files
(x86)\Ziena\KNITRO900/include"   -O2 -Wall  -mtune=core2 -c knitro.cpp -o
knitro.o
g++ -m64 -shared -s -static-libgcc -o knitroR.dll tmp.def RcppExports.o
knitro.o C:\Program Files (x86)\Ziena\KNITRO900\lib\knitro900.lib
-Ld:/RCompile/CRANpkg/extralibs64/local/lib/x64
-Ld:/RCompile/CRANpkg/extralibs64/local/lib -LC:/R/bin/x64 -lR
knitro.o:knitro.cpp:(.text+0x6e0): undefined reference to `KTR_new'
knitro.o:knitro.cpp:(.text+0x72a): undefined reference to
`KTR_load_param_file'
knitro.o:knitro.cpp:(.text+0x74d): undefined reference to
`KTR_get_int_param_by_name'
knitro.o:knitro.cpp:(.text+0x7b7): undefined reference to
`KTR_set_int_param_by_name'
knitro.o:knitro.cpp:(.text+0x859): undefined reference to
`KTR_set_int_param_by_name'
knitro.o:knitro.cpp:(.text+0x8b3): undefined reference to
`KTR_get_int_param_by_name'
knitro.o:knitro.cpp:(.text+0x8f3): undefined reference to
`KTR_get_int_param_by_name'
knitro.o:knitro.cpp:(.text+0x92e): undefined reference to
`KTR_set_func_callback'
knitro.o:knitro.cpp:(.text+0x955): undefined reference to
`KTR_set_grad_callback'
knitro.o:knitro.cpp:(.text+0xa29): undefined reference to`KTR_init_problem'
knitro.o:knitro.cpp:(.text+0xaff): undefined reference to `KTR_solve'
knitro.o:knitro.cpp:(.text+0xb4a): undefined reference to
`KTR_get_number_iters'
knitro.o:knitro.cpp:(.text+0xb5e): undefined reference to
`KTR_get_number_FC_evals'
knitro.o:knitro.cpp:(.text+0xb72): undefined reference to
`KTR_get_number_GA_evals'
knitro.o:knitro.cpp:(.text+0xb86): undefined reference to `KTR_free'
knitro.o:knitro.cpp:(.text+0x1335): undefined reference to
`KTR_set_int_param_by_name'
knitro.o:knitro.cpp:(.text+0x1821): undefined reference to
`KTR_set_int_param_by_name'
collect2: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'knitroR'
- removing 'C:/R/library/knitroR'
  Warning in install.packages :
  running command '"C:/R/bin/i386/R" CMD INSTALL -l "C:\R\library"
  "C:/knitroR-master"' had status 1
  Warning in install.packages :
  installation of package ‘C:/knitroR-master’ had non-zero exit status

2015-01-11 22:31 GMT-03:00 Jan Tilly notifications@github.com:

**Comment by jtilly** [comment]
The link to the knitro library doesn't seem to work.

Can you check if the following file exists? C:\Program Files (x86)\Ziena\KNITRO900\lib\knitro900.lib
If it does then please download the latest [Makevars.win](https://github.com/jtilly/knitroR/blob/master/src/Makevars.win) and see if the latest change I made helps. Obviously you need change KNRELEASE again.

**Comment by mbanco** [comment]
I used the latest Makevars.win and this is the compilation error:


install.packages("C:/knitroR-master", repos = NULL, type="source")
* installing *source* package 'knitroR' ...
** libs

*** arch - i386
cygwin warning:
  MS-DOS style path detected: C:/R/etc/i386/Makeconf
  Preferred POSIX equivalent is: /cygdrive/c/R/etc/i386/Makeconf
  CYGWIN environment variable option "nodosfilewarning" turns off this
warning.
  Consult the user's guide for more details about POSIX paths:
    http://cygwin.com/cygwin-ug-net/using.html#using-pathnames
g++ -m32 -I"C:/R/include" -DNDEBUG    -I"C:/R/library/Rcpp/include"
-I"d:/RCompile/CRANpkg/extralibs64/local/include"  -I"C:\Program Files
(x86)\Ziena\KNITRO900/include"   -O2 -Wall  -mtune=core2 -c RcppExports.cpp
-o RcppExports.o
g++ -m32 -I"C:/R/include" -DNDEBUG    -I"C:/R/library/Rcpp/include"
-I"d:/RCompile/CRANpkg/extralibs64/local/include"  -I"C:\Program Files
(x86)\Ziena\KNITRO900/include"   -O2 -Wall  -mtune=core2 -c knitro.cpp -o
knitro.o
Syntax error: "(" unexpected (expecting "fi")
make: *** [knitroR.dll] Error 2
Aviso: comando ejecutado 'make -f "Makevars.win" -f
"C:/R/etc/i386/Makeconf" -f "C:/R/share/make/winshlib.mk"
SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)'
SHLIB="knitroR.dll" OBJECTS="RcppExports.o knitro.o"' tiene estatus 2
ERROR: compilation failed for package 'knitroR'
* removing 'C:/R/library/knitroR'
Warning in install.packages :
  running command '"C:/R/bin/i386/R" CMD INSTALL -l "C:\R\library"
"C:/knitroR-master"' had status 1
Warning in install.packages :
  installation of package ‘C:/knitroR-master’ had non-zero exit status

2015-01-15 17:03 GMT-03:00 Jan Tilly <notifications@github.com>:

**Comment by jtilly** [comment]
Alright. Apparently, the last change to Makevars.win wasn't a good idea. I changed it back. 

Can you check if the following file exists? C:\Program Files (x86)\Ziena\KNITRO900\lib\knitro900.lib

If it does, then you need to figure out why we cannot link to it. My best guess is that either the space or the parentheses in the path might cause some issues and you need to escape them somehow. I don't have access to a Windows machine right now, so I can only guess. 

If the file doesn't exist, then `KNLIB_DYNAMIC` is pointing to the wrong library file and needs to be adjusted.

**Comment by mbanco** [comment]
The file C:\Program Files (x86)\Ziena\KNITRO900\lib\knitro900.lib exists.

2015-01-15 18:48 GMT-03:00 Jan Tilly <notifications@github.com>:

**Comment by jtilly** [comment]
Okay, that's a start. As far as I can tell the linking against knitro900.lib fails. This happens in `Makevars.win` in this line: 

`PKG_LIBS = $(shell "$(R_HOME)/bin$(R_ARCH_BIN)/Rscript.exe" -e "Rcpp:::LdFlags()") $(KNLIB_DYNAMIC)`

You may want to play around with different ways of specifying the link against `C:\Program Files (x86)\Ziena\KNITRO900\lib\knitro900.lib`. I don't have access to a Windows computer right now, so I can't test any of it. A good way to start would be to look at the C++ examples in your Knitro folder and take a look at the `makefile` there and replicate the way it's linking against the `knitro900.lib`.

Sorry that I can't be more specific right now.

**Comment by jtilly** [comment]
I'm just looking at this again: It appears as if the 32bit installation works fine. It's only the 64 bit installation that causes problems. This isn't surprising if you don't have a 64bit version of Knitro installed on your computer. 

Can you turn off multiarch support when you build the package? 

Download the source code of the package and then install it using

```
install.packages("C:\path\to\knitroR-master", INSTALL_opts="--no-multiarch", repos=NULL, type="source")
```

**Comment by mbanco** [comment]
Hi,

It Works fine.
Excellent Job.

Thanks

2015-03-27 12:00 GMT-03:00 Jan Tilly notifications@github.com:
